File upload script
tomerlichtash/mels-loop pull request #354
Opened 2023-06-18 22:38 UTC by imdfl

$ `yarn upload <path> [path ...] [--tags tag1 [tag2...]]`

scripts/.env file in private message

2023-06-19 20:16 UTC, tomerlichtash requested changes
I don't have the script to upload my appreciation for this. Excellent stuff.
Added some minor type/infra comments.

Will check out the lint issue.
Also, for some reason build doesn't run properly (not because of lint).

2023-06-19 20:16 UTC, tomerlichtash commented on package.json
> +		"aws": "^0.0.3-2",
```
		"aws": "^0.0.3-2",
		"aws-sdk": "^2.1399.0",
```
Can this be a Dev Dependency instead of a regular dependency?

2023-06-20 22:41 UTC, imdfl commented on tsconfig.json
> +		"src/*.ts",
Reverted, added exclude

2023-06-20 22:43 UTC, imdfl commented on scripts/s3-client.ts
> +			this._client = new (S3Client as any)({
tsc doesn't recognize the constructor even tho it knows the class. Odd, but I didn't investigate.

2023-06-20 22:45 UTC, imdfl commented on scripts/list-media.ts
> +listObjects().then((response: any) => {
typed, but typescript is the default, it's the path of least effort, so if any happens to gets things done, it's not antithetic to the platform.

2023-06-20 22:49 UTC, imdfl commented on scripts/list-media.ts
> +
fixed

2023-06-20 22:49 UTC, imdfl commented
@tomerlichtash , please review

2023-06-21 04:53 UTC, imdfl commented on scripts/package.json
> +    "@aws-sdk/client-s3": "^3.354.0",
fixed

2023-06-21 06:18 UTC, tomerlichtash commented on scripts/s3-client.ts
> +			this._client = new (S3Client as any)({
Try just to remove `any`:

```
			this._client = new S3Client({
				region: this.region,
			});
```

On my machine it resolved fine, and referring to the type.

2023-06-21 06:20 UTC, tomerlichtash commented on scripts/tsconfig.json
> +		// "lib": [],                             /* Specify library files to be included in the compilation. */
Let's keep only what we need in this tsconfig. Unless you want that configuration for later.

2023-06-21 06:22 UTC, tomerlichtash commented
@imdfl - Can you please also add an _EMPTY_ `.env` file to the scripts folder?

```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_BUCKET=
AWS_REGION=
```

2023-06-21 06:38 UTC, tomerlichtash commented
> @imdfl - Can you please also add an _EMPTY_ `.env` file to the scripts folder?
> 
> ```
> AWS_ACCESS_KEY_ID=
> AWS_SECRET_ACCESS_KEY=
> AWS_BUCKET=
> AWS_REGION=
> ```
> 
> After comitting this file, add `*.env` to `.gitignore`, to prevent an accidental push.

Please disregard for now. We'll try vercel's CLI which has a method to pull env vars.

2023-06-21 07:24 UTC, imdfl commented
How do you envision the upload script running on a vercel machine?

I can extend the script so that it accepts s3 urls in addition to local paths. Then you can upload a file from one bucket to another. Later I can add a script to upload a local file to the s3 bucket from which the final upload will be performed. That script will require different env variables, no biggie. To allow the second script to run on vercel, we will need to support uploading from a third bucket, but this is already solved.

2023-06-21 11:43 UTC, tomerlichtash commented
> How do you envision the upload script running on a vercel machine?

I merely referred to the idea of a secret manager, that we get from Vercel. I'm not sure if this is relevant without a Pro Plan, otherwise no one but me would be able to access it, but generally the idea is to run a CLI that will clone an .env file to your dev env. Perhaps this can be achieved with another service, researching it now.

> I can extend the script so that it accepts s3 urls in addition to local paths. Then you can upload a file from one bucket to another. Later I can add a script to upload a local file to the s3 bucket from which the final upload will be performed. That script will require different env variables, no biggie. To allow the second script to run on vercel, we will need to support uploading from a third bucket, but this is already solved.

Not sure I follow the use case here.

2023-06-22 03:18 UTC, imdfl commented on scripts/s3-client.ts
> +			this._client = new (S3Client as any)({
no idea what has changed, but it compiles fine now.

2023-06-25 12:02 UTC, tomerlichtash approved these changes

2023-06-25 12:24 UTC, merged